### ISSUE TITLE
How can l test the connection migration?

### ISSUE THREAD

**Issue by Karthikdasari0423** [tbarbette/wrk-quic#1]
Thanks for your contribution @tbarbette 
Can you tell me how to test the connection migration?

**Comment by tbarbette** [comment]
Do you mean QUIC connection migration, ie over multipath?  This is not supported for now. If you refer to the previous work of Haoran Yao (https://www.diva-portal.org/smash/get/diva2:1539441/FULLTEXT01.pdf) this is transparent server based migration, so the client is not aware.
