### ISSUE TITLE
picoquic-create not found 

### ISSUE THREAD

**Issue by NithishK2002** [tbarbette/wrk-quic#2]
![Screenshot from 2024-04-17 18-23-55](https://github.com/tbarbette/wrk-quic/assets/93331531/ea8ed151-60ef-40b6-bf19-8fcc6eed7ceb)

Here I am trying to build wrk-quic but it shows there is no picoquic-create in picoquic-core module

**Comment by tbarbette** [comment]
Would you have an old picoquic maybe? I see it's available in the latest picoquic. Can you check the picoquic-core library with objdump?

**Comment by NithishK2002** [comment]
I tried building picoquic from here https://github.com/private-octopus/picoquic 
![image](https://github.com/tbarbette/wrk-quic/assets/93331531/5f0a8942-ed30-4e6d-b2b7-cce1192cba62)
I think there is picoquic-core lib but it shows PIcoquic not found....

**Comment by tbarbette** [comment]
Is this repository checked out in wrk2?

Maybe something was updated in picoquic, there's no versioning so I'll try to find a working commit.

**Comment by tbarbette** [comment]
Picotls added a new library used in picoquic. As they refuse to create a proper install system like pkgconfig, I can't automatize the libraries to be added... 

Anyway, it's fixed.
